---
- name: ensure mysql is running
  service: name=mysql state=started enabled=yes
 #- name: Copy ~/.my.cnf to nodes
 # copy: src=/etc/mysql/my.cnf dest=/root/.my.cnf
 # become: yes

- name: create mysql database
  mysql_db: 
        login_unix_socket=/var/run/mysqld/mysqld.sock
        login_user=root
        login_password=Devops@123!@#
        name={{ wp_mysql_db }} 
        state=present
  become: yes

- name: Create Mysql username and password
  mysql_user:
        login_unix_socket=/var/run/mysqld/mysqld.sock
        login_user=root
        login_password=Devops@123!@#
        name={{ wp_mysql_user }}
        password={{ wp_mysql_password }}
        priv=*.*:ALL
  become: yes


