---
  - name: launching AWS instance using Ansible
    ec2:
       key_name: awskey
       instance_type: t2.micro
       image: ami-0277b52859bac6f4b
       region: us-east-2
       wait: yes
       count: 1
       vpc_subnet_id: subnet-b70649fb
       group: webserver
       assign_public_ip: yes
       instance_tags:
               Name: server2
       user_data: "{{ lookup('file', 'user_data.sh') }}"
       aws_access_key: "{{ access_key }}" 
       aws_secret_key: "{{ secret_key }}"
       instance_profile_name: role2
