---
 - name: create a role
   iam_role:
          name: role2
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          assume_role_policy_document: "{{ lookup('file','policy.json') }}"
          managed_policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          description: This is My New Role
          state: present
