---
  - name: Create an S3 bucket
    aws_s3:
            aws_access_key: "{{ access_key }}"
            aws_secret_key: "{{ secret_key }}"
            bucket: vabbucket123
            permission: public-read-write
            mode: create
            region: us-east-2


  - name: add file to s3 bucket
    aws_s3:
           aws_access_key: "{{ access_key }}"
           aws_secret_key: "{{ secret_key }}"
           bucket: vabbucket123
           object: index.html
           src: files/index.html
           mode: put
